{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-this-is-a-test
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_this_is_a_test
    - qiime2.plugins.this_is_a_test
  commands:
    - pytest --cov q2_this_is_a_test --pyargs q2_this_is_a_test

about:
  home: https://github.com/bokulich-lab/q2-this-is-a-test
  license: BSD-3-Clause
  license_family: BSD
